### ISSUE TITLE
Do not print in createMoney

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-KorawitRupanya#10]
https://github.com/OOP2018/coinpurse-KorawitRupanya/blob/59fedf717956411f690b4f279ee81f7908a1f1d8/src/coinpurse/MoneyFactory.java#L53
Printing does not belong to `MoneyFactory`, it is `ConsoleDialog`'s job.
So what you need to do is just put the message to go along with your `IllegalArgumentException` like,
```
throw new IllegalArgumentException("my error message", e);
```
And the message would be handled elsewhere.

**Comment by KorawitRupanya** [comment]
Already done 👍
