### ISSUE TITLE
Additional method should be private

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-KorawitRupanya#11]
Methods such as `public boolean coin(double value)` should be private.
Also, a method that return a boolean value, we usually naming it to start with `is` or `has`.
For example, `isCoin`, so that it is more readable.
```
// easier to read
if (isCoin(value)) {
   return new Coin(value, "Baht");
}
```

**Comment by KorawitRupanya** [comment]
Already done 👍
