### ISSUE TITLE
Logic error!!

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-KorawitRupanya#5]
https://github.com/OOP2018/coinpurse-KorawitRupanya/blob/bcb5ce122cec43a9178608ea7cbf874ac53fe37b/src/coinpurse/ValueComparator.java#L13-L24

**Comment by KorawitRupanya** [comment]
already done 👍

**Comment by taveratch** [comment]
still wrong, did you read the instruction?

**Comment by KorawitRupanya** [comment]
just do it again,I wonder if this will right now.

**Comment by taveratch** [comment]
You should check your code that satisfies every requirement before submitting. Next time your score will be deducted permanently.
