### ISSUE TITLE
Duplicate code in withdraw()

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-KorawitRupanya#7]
<img width="702" alt="screen shot 2561-02-12 at 22 08 10" src="https://user-images.githubusercontent.com/8603253/36103579-4f0ea638-1042-11e8-85b0-22028a1edae1.png">

https://github.com/OOP2018/coinpurse-KorawitRupanya/blob/58ccd15fcef1eb5d6a2f15326784dc9773a3c1b6/src/coinpurse/Purse.java#L97-L162

**Comment by KorawitRupanya** [comment]
already done:)
